import {NextResponse} from "next/server";
type Msg={role:"user"|"assistant";content:string}; type Att={name:string;type:string;data:string};
const hits=new Map<string,{count:number;reset:number}>();
function allowed(req:Request){const ip=req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"local",now=Date.now(),slot=hits.get(ip);if(!slot||slot.reset<now){hits.set(ip,{count:1,reset:now+60000});return true}if(slot.count>=20)return false;slot.count++;return true}
export async function POST(req:Request){try{if(!allowed(req))return NextResponse.json({error:"Trop de requêtes. Réessayez dans une minute."},{status:429});const key=process.env.OPENAI_API_KEY;if(!key)return NextResponse.json({error:"Le moteur IA n'est pas configuré."},{status:503});
 const body=await req.json();const raw:Msg[]=Array.isArray(body.messages)?body.messages:[];const history=raw.slice(-30).filter(m=>(m.role==="user"||m.role==="assistant")&&typeof m.content==="string").map(m=>({role:m.role,content:m.content.slice(0,12000)}));if(!history.length)return NextResponse.json({error:"Message manquant."},{status:400});
 const atts:Att[]=Array.isArray(body.attachments)?body.attachments.slice(0,4):[];const last=history[history.length-1];let input:any[]=history.slice(0,-1);const parts:any[]=[{type:"input_text",text:last.content}];
 for(const a of atts){if(typeof a?.data!=="string"||a.data.length>12000000)continue;if((a.type||"").startsWith("image/"))parts.push({type:"input_image",image_url:a.data});else if(a.type==="application/pdf"||a.type==="text/plain")parts.push({type:"input_file",filename:a.name||"document",file_data:a.data});}
 input.push({role:"user",content:parts});const mode=body.mode==="Work"?"Work":"Chat";const instructions=mode==="Work"?"Tu es AlexIA en mode Work. Analyse aussi les pièces jointes. Structure les missions, sois factuelle et ne prétends jamais avoir exécuté une action non exécutée. Réponds en français.":"Tu es AlexIA, une IA personnelle utile, concise et fiable. Analyse les images et documents joints quand ils sont présents. Réponds en français par défaut.";
 const q=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-5.6",instructions,input,max_output_tokens:1800})});const data=await q.json();if(!q.ok)return NextResponse.json({error:data?.error?.message||"Erreur du fournisseur IA"},{status:q.status});const reply=data.output_text||data.output?.flatMap((o:any)=>o.content||[]).filter((c:any)=>c.type==="output_text").map((c:any)=>c.text||"").join("\n")||"Je n'ai pas reçu de réponse exploitable.";return NextResponse.json({reply});
 }catch(e){return NextResponse.json({error:"Impossible de traiter la demande."},{status:500})}}
