"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
type Msg={role:"user"|"assistant";content:string};
type SpeechRecognitionEventLike={results:{[key:number]:{[key:number]:{transcript:string}}}};
export default function Home(){
 const[mode,setMode]=useState<"Chat"|"Work">("Chat"),[messages,setMessages]=useState<Msg[]>([]),[input,setInput]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[listening,setListening]=useState(false),[voice,setVoice]=useState(true);const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{try{setMessages(JSON.parse(localStorage.getItem("alexia-history")||"[]"))}catch{}},[]);
 useEffect(()=>{localStorage.setItem("alexia-history",JSON.stringify(messages));end.current?.scrollIntoView({behavior:"smooth"})},[messages]);
 function speak(text:string){if(!voice||typeof window==="undefined")return;const a=(window as any).AlexiaAndroid;if(a?.speak){a.speak(text);return}if(!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="fr-FR";const vs=window.speechSynthesis.getVoices();u.voice=vs.find(v=>v.lang.startsWith("fr")&&/female|audrey|hortense|denise/i.test(v.name))||vs.find(v=>v.lang.startsWith("fr"))||null;window.speechSynthesis.speak(u)}
 async function send(e?:FormEvent,spoken?:string){e?.preventDefault();const text=(spoken??input).trim();if(!text||busy)return;const next=[...messages,{role:"user" as const,content:text}];setMessages(next);setInput("");setBusy(true);setError("");
  try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:next,mode})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Erreur IA");setMessages([...next,{role:"assistant",content:data.reply}]);speak(data.reply)}catch(err){setError(err instanceof Error?err.message:"Erreur de connexion")}finally{setBusy(false)}
 }
 useEffect(()=>{(window as any).__alexiaVoiceResult=(t:string)=>{setListening(false);setInput(t);send(undefined,t)};(window as any).__alexiaVoiceError=()=>{setListening(false);setError("Je n’ai pas pu entendre. Réessayez.")};return()=>{delete (window as any).__alexiaVoiceResult;delete (window as any).__alexiaVoiceError}},[messages,busy,mode]);\n function listen(){const a=(window as any).AlexiaAndroid;if(a?.listen){setListening(true);a.listen();return}const w=window as unknown as {SpeechRecognition?:new()=>any;webkitSpeechRecognition?:new()=>any};const R=w.SpeechRecognition||w.webkitSpeechRecognition;if(!R){setError("La reconnaissance vocale n’est pas disponible dans ce navigateur.");return}const r=new R();r.lang="fr-FR";r.interimResults=false;r.continuous=false;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onerror=()=>{setListening(false);setError("Je n’ai pas pu entendre. Réessayez.")};r.onresult=(e:SpeechRecognitionEventLike)=>{const t=e.results[0][0].transcript;setInput(t);send(undefined,t)};r.start()}
 function reset(){setMessages([]);localStorage.removeItem("alexia-history");window.speechSynthesis?.cancel()}
 return <main><aside><div className="logo">A<span>✦</span></div><h1>AlexIA</h1><p>Votre IA personnelle</p><nav><button className={mode==="Chat"?"active":""} onClick={()=>setMode("Chat")}>💬 Chat</button><button className={mode==="Work"?"active":""} onClick={()=>setMode("Work")}>⚡ Work</button><button onClick={reset}>◷ Nouvelle conversation</button><button>⌘ Connexions</button></nav></aside><section><header><div><b>{mode}</b><small>{mode==="Work"?"Mission autonome":"Conversation intelligente"}</small></div><i>● disponible</i></header>
 {messages.length===0?<div className="hero"><div className="orb">A✦</div><h2>Bonjour, je suis AlexIA.</h2><p>{mode==="Work"?"Confiez-moi une mission : je la structure, l’analyse et vous rends compte.":"Écrivez-moi ou touchez le micro pour me parler. Je peux aussi vous répondre à voix haute."}</p><div className="chips"><button onClick={()=>setInput("Aide-moi à continuer mes projets")}>Continuer mes projets</button><button onClick={()=>setInput("Analyse ce que je vais te transmettre")}>Analyser un document</button><button onClick={()=>{setMode("Work");setInput("Prépare un plan d’action pour cette mission : ")}}>Préparer une mission</button></div></div>:
 <div className="conversation">{messages.map((m,i)=><div key={i} className={"msg "+m.role}><b>{m.role==="user"?"Vous":"AlexIA"}</b><p>{m.content}</p></div>)}{busy&&<div className="msg assistant"><b>AlexIA</b><p>Je réfléchis…</p></div>}<div ref={end}/></div>}
 <form className="composer" onSubmit={send}><label title="Joindre un fichier" style={{cursor:"pointer",fontSize:24}}>📎<input type="file" accept="image/*,.pdf,.txt,.doc,.docx" multiple style={{display:"none"}} onChange={e=>{const names=Array.from(e.target.files||[]).map(f=>f.name);if(names.length)setInput(v=>v+(v?"\\n":"")+"Pièce(s) jointe(s) : "+names.join(", "))}}/></label><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder={listening?"Je vous écoute…":mode==="Work"?"Décrivez la mission à exécuter…":"Écrivez ou parlez à AlexIA…"} /><button type="button" className="send" onClick={listen} aria-label="Parler à AlexIA">{listening?"◉":"🎤"}</button><button className="send" disabled={busy}>➜</button><button type="button" onClick={()=>setVoice(v=>!v)} aria-label="Réponse vocale">{voice?"🔊":"🔇"}</button>{error?<small className="error">{error}</small>:<small>AlexIA • Chat + Work • voix {voice?"active":"coupée"}</small>}</form></section></main>
}