"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
type Msg={role:"user"|"assistant";content:string};
export default function Home(){
 const[mode,setMode]=useState<"Chat"|"Work">("Chat"),[messages,setMessages]=useState<Msg[]>([]),[input,setInput]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{try{setMessages(JSON.parse(localStorage.getItem("alexia-history")||"[]"))}catch{}},[]);
 useEffect(()=>{localStorage.setItem("alexia-history",JSON.stringify(messages));end.current?.scrollIntoView({behavior:"smooth"})},[messages]);
 async function send(e?:FormEvent){e?.preventDefault();const text=input.trim();if(!text||busy)return;const next=[...messages,{role:"user" as const,content:text}];setMessages(next);setInput("");setBusy(true);setError("");
  try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:next,mode})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Erreur IA");setMessages([...next,{role:"assistant",content:data.reply}])}catch(err){setError(err instanceof Error?err.message:"Erreur de connexion")}finally{setBusy(false)}
 }
 function reset(){setMessages([]);localStorage.removeItem("alexia-history")}
 return <main><aside><div className="logo">A<span>✦</span></div><h1>AlexIA</h1><p>Votre IA personnelle</p><nav><button className={mode==="Chat"?"active":""} onClick={()=>setMode("Chat")}>💬 Chat</button><button className={mode==="Work"?"active":""} onClick={()=>setMode("Work")}>⚡ Work</button><button onClick={reset}>◷ Nouvelle conversation</button><button>⌘ Connexions</button></nav></aside><section><header><div><b>{mode}</b><small>{mode==="Work"?"Mission autonome":"Conversation intelligente"}</small></div><i>● disponible</i></header>
 {messages.length===0?<div className="hero"><div className="orb">A✦</div><h2>Bonjour, je suis AlexIA.</h2><p>{mode==="Work"?"Confiez-moi une mission : je la structure, l’analyse et vous rends compte.":"Posez-moi une question. Je garde l’historique de cette conversation sur cet appareil."}</p><div className="chips"><button onClick={()=>setInput("Aide-moi à continuer mes projets")}>Continuer mes projets</button><button onClick={()=>setInput("Analyse ce que je vais te transmettre")}>Analyser un document</button><button onClick={()=>{setMode("Work");setInput("Prépare un plan d’action pour cette mission : ")}}>Préparer une mission</button></div></div>:
 <div className="conversation">{messages.map((m,i)=><div key={i} className={"msg "+m.role}><b>{m.role==="user"?"Vous":"AlexIA"}</b><p>{m.content}</p></div>)}{busy&&<div className="msg assistant"><b>AlexIA</b><p>Je réfléchis…</p></div>}<div ref={end}/></div>}
 <form className="composer" onSubmit={send}><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder={mode==="Work"?"Décrivez la mission à exécuter…":"Écrivez à AlexIA…"} /><button className="send" disabled={busy}>➜</button>{error?<small className="error">{error}</small>:<small>AlexIA • Chat + Work • historique local</small>}</form></section></main>
}